
job_584f5c92-759d-4bbc-92af-c212da78daed:
  video_path: "/Volumes/FREDDY FILES/ANTIGRAVITY/1001-VIDEO AVATAR/api_server/app/static/avatars/marcus_aurelius.jpg"
  audio_path: "processing/584f5c92-759d-4bbc-92af-c212da78daed/speech.wav"
